#### Getting Started with Pytorch

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True


In [ ]:
import torch

# ------------------ 1. Creating Tensors from Lists ------------------
print("# Creating tensors from Python lists")

x = torch.tensor([1, 2, 3])              # 1D Tensor (vector)
y = torch.tensor([[1, 2], [3, 4]])       # 2D Tensor (matrix)

print("1D Tensor (x):\n", x)
print("2D Tensor (y):\n", y)

# ------------------ 2. Zeros and Ones ------------------
print("\n# Creating zeros and ones tensors")

zeros = torch.zeros(2, 3)
ones = torch.ones(3, 2)

print("Zeros tensor:\n", zeros)
print("Ones tensor:\n", ones)

# ------------------ 3. Random Tensors ------------------
print("\n# Creating random tensors")

uniform_rand = torch.rand(2, 2)   # Uniform distribution [0, 1)
normal_rand = torch.randn(2, 2)   # Normal distribution (mean=0, std=1)

print("Uniform random:\n", uniform_rand)
print("Normal random:\n", normal_rand)

# ------------------ 4. Identity Matrix ------------------
print("\n# Creating identity matrix")

identity = torch.eye(3)
print("Identity matrix:\n", identity)

# ------------------ 5. Range and Linspace ------------------
print("\n# Creating sequences")

arange_tensor = torch.arange(0, 10, 2)      # 0, 2, 4, 6, 8
linspace_tensor = torch.linspace(0, 1, 5)   # 5 points between 0 and 1

print("Arange:\n", arange_tensor)
print("Linspace:\n", linspace_tensor)


# Creating tensors from Python lists
1D Tensor (x):
 tensor([1, 2, 3])
2D Tensor (y):
 tensor([[1, 2],
        [3, 4]])

# Creating zeros and ones tensors
Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

# Creating random tensors
Uniform random:
 tensor([[0.5173, 0.1884],
        [0.7933, 0.6762]])
Normal random:
 tensor([[-0.1416,  0.6291],
        [-0.0995,  0.8378]])

# Creating identity matrix
Identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Creating sequences
Arange:
 tensor([0, 2, 4, 6, 8])
Linspace:
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [ ]:
import torch

# ------------------ 6. Shape & Reshape ------------------
print("\n# Shape and Reshape")

a = torch.randn(2, 3, 4)
print("Original tensor (2x3x4):\n", a)

reshaped = a.reshape(3, 8)
print("Reshaped to (3x8):\n", reshaped)

flattened = a.view(-1)
print("Flattened tensor:\n", flattened)

squeezed = torch.tensor([[[5]]]).squeeze()
print("Squeezed tensor (remove 1D dims):\n", squeezed)

unsqueezed = torch.tensor([5]).unsqueeze(0)
print("Unsqueezed tensor (add new dim):\n", unsqueezed)

# ------------------ 7. Mathematical Operations ------------------
print("\n# Element-wise math operations")

x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)
print("x / y =", x / y)
print("x ** 2 =", x ** 2)

# Matrix multiplication
print("\n# Matrix multiplication")

A = torch.randn(2, 3)
B = torch.randn(3, 4)
C = torch.matmul(A, B)  # or A @ B

print("A:\n", A)
print("B:\n", B)
print("A @ B:\n", C)

# ------------------ 8. Indexing & Slicing ------------------
print("\n# Indexing and slicing")

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("First row:", x[0])
print("Second column:", x[:, 1])
print("Element at row 1, col 2:", x[1, 2])
print("Slice [0:1, 0:2]:\n", x[0:1, 0:2])

# ------------------ 9. Stacking Tensors ------------------
print("\n# Stacking and concatenating")

a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

stacked = torch.stack([a, b])
cat_dim0 = torch.cat([a.unsqueeze(0), b.unsqueeze(0)], dim=0)
cat_dim1 = torch.cat([a.unsqueeze(1), b.unsqueeze(1)], dim=1)

print("Stacked:\n", stacked)
print("Concatenated (dim=0):\n", cat_dim0)
print("Concatenated (dim=1):\n", cat_dim1)

# ------------------ 10. In-place Operations ------------------
print("\n# In-place operations")

x = torch.tensor([1, 2, 3])
x.add_(1)
print("After x.add_(1):", x)
x.mul_(2)
print("After x.mul_(2):", x)

# ------------------ 11. Type Conversion ------------------
print("\n# Type casting")

x = torch.tensor([1.5, 2.8])
print("Float to int:", x.int())
print("Float to bool:", x.bool())

# ------------------ 12. Saving and Loading Tensors ------------------
print("\n# Saving and loading tensors")

x = torch.tensor([10, 20, 30])
torch.save(x, "x.pt")
loaded = torch.load("x.pt")
print("Loaded tensor:\n", loaded)

# ------------------ 13. Logical Operations ------------------
print("\n# Logical operations")

a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

print("a == b:", a == b)
print("a > b:", a > b)
print("All a < b:", torch.all(a < b))
print("Any a > 2:", torch.any(a > 2))



# Shape and Reshape
Original tensor (2x3x4):
 tensor([[[-0.4756, -0.7412, -0.7264,  1.2327],
         [-0.5822,  0.7414, -0.0418,  1.1094],
         [ 1.8119,  1.3267, -2.0836, -0.5554]],

        [[ 0.4153, -0.8315, -0.4005, -0.9169],
         [ 0.4011, -0.4542,  0.1758, -0.2307],
         [ 0.2598, -1.4258, -0.6101, -0.9190]]])
Reshaped to (3x8):
 tensor([[-0.4756, -0.7412, -0.7264,  1.2327, -0.5822,  0.7414, -0.0418,  1.1094],
        [ 1.8119,  1.3267, -2.0836, -0.5554,  0.4153, -0.8315, -0.4005, -0.9169],
        [ 0.4011, -0.4542,  0.1758, -0.2307,  0.2598, -1.4258, -0.6101, -0.9190]])
Flattened tensor:
 tensor([-0.4756, -0.7412, -0.7264,  1.2327, -0.5822,  0.7414, -0.0418,  1.1094,
         1.8119,  1.3267, -2.0836, -0.5554,  0.4153, -0.8315, -0.4005, -0.9169,
         0.4011, -0.4542,  0.1758, -0.2307,  0.2598, -1.4258, -0.6101, -0.9190])
Squeezed tensor (remove 1D dims):
 tensor(5)
Unsqueezed tensor (add new dim):
 tensor([[5]])

# Element-wise math operations
x + y = tensor(